/**
 * Realistic component templates for the landing playground.
 *
 * Each template is a plain string with a `__SEED__` placeholder that the
 * client replaces with the user's typed seed. Strings use concatenation
 * (no template literals) so that the runtime ${...} tokens visible in the
 * code samples (e.g. ${user.id}) survive verbatim into the output instead
 * of being interpreted as TS interpolations during the outer landing build.
 *
 * The whole object is serialized via JSON.stringify and embedded into the
 * landing page's <script> block. JSON encoding handles all escaping for us.
 */

const API = 'https://navii-api.uxderrick.com';
const NL = '\n';

type Framework = 'html' | 'react' | 'next' | 'vue' | 'svelte' | 'curl' | 'fetch' | 'url';
type Usecase = 'profile' | 'team' | 'comment' | 'fallback' | 'group' | 'url';

type TemplateMap = Record<Usecase, Partial<Record<Framework, string>>>;

const join = (...lines: string[]) => lines.join(NL);

export const TEMPLATES: TemplateMap = {
  // ── Profile card ───────────────────────────────────────────────────────
  profile: {
    html: join(
      '<div class="user-card">',
      '  <img src="' + API + '/avatar/__SEED__?size=96&tileBg=auto" alt="__SEED__" width="64" height="64" />',
      '  <div>',
      '    <strong>__SEED__</strong>',
      '    <span>Member</span>',
      '  </div>',
      '</div>',
    ),
    react: join(
      '// example user.id: "__SEED__"',
      'function UserCard({ user }) {',
      '  return (',
      '    <div className="user-card">',
      '      <img',
      '        src={`' + API + '/avatar/${encodeURIComponent(user.id)}?size=96&tileBg=auto`}',
      '        alt={user.name}',
      '        width={64}',
      '        height={64}',
      '      />',
      '      <div>',
      '        <strong>{user.name}</strong>',
      '        <span>{user.email}</span>',
      '      </div>',
      '    </div>',
      '  );',
      '}',
    ),
    next: join(
      "import Image from 'next/image';",
      '',
      'export function UserCard({ user }) {',
      '  return (',
      '    <div className="user-card">',
      '      <Image',
      '        src={`' + API + '/avatar/${encodeURIComponent(user.id)}?size=96&tileBg=auto`}',
      '        alt={user.name}',
      '        width={64}',
      '        height={64}',
      '        unoptimized',
      '      />',
      '      <strong>{user.name}</strong>',
      '    </div>',
      '  );',
      '}',
    ),
    vue: join(
      '<template>',
      '  <div class="user-card">',
      '    <img',
      '      :src="`' + API + '/avatar/${encodeURIComponent(user.id)}?size=96&tileBg=auto`"',
      '      :alt="user.name"',
      '      width="64"',
      '      height="64"',
      '    />',
      '    <strong>{{ user.name }}</strong>',
      '  </div>',
      '</template>',
    ),
    svelte: join(
      '<script>export let user;</script>',
      '',
      '<div class="user-card">',
      '  <img',
      '    src={`' + API + '/avatar/${encodeURIComponent(user.id)}?size=96&tileBg=auto`}',
      '    alt={user.name}',
      '    width="64"',
      '    height="64"',
      '  />',
      '  <strong>{user.name}</strong>',
      '</div>',
    ),
    curl: "curl -o avatar.png \\" + NL + "  '" + API + "/avatar/__SEED__?size=256&tileBg=auto'",
    fetch: join(
      "const userId = '__SEED__';",
      'const res = await fetch(`' + API + '/avatar/${encodeURIComponent(userId)}?size=96&tileBg=auto`);',
      'const svg = await res.text();',
    ),
    url: 'GET ' + API + '/avatar/__SEED__?size=96&tileBg=auto',
  },

  // ── Team list (iteration) ──────────────────────────────────────────────
  team: {
    html: join(
      '<ul class="team">',
      '  <li><img src="' + API + '/avatar/__SEED__?size=48" alt="__SEED__" /></li>',
      '  <li><img src="' + API + '/avatar/bob?size=48"   alt="bob" /></li>',
      '  <li><img src="' + API + '/avatar/carol?size=48" alt="carol" /></li>',
      '  <li><img src="' + API + '/avatar/dave?size=48"  alt="dave" /></li>',
      '</ul>',
    ),
    react: join(
      'const team = [',
      "  { id: '__SEED__', name: 'Alice' },",
      "  { id: 'bob',     name: 'Bob' },",
      "  { id: 'carol',   name: 'Carol' },",
      "  { id: 'dave',    name: 'Dave' },",
      '];',
      '',
      'export function Team() {',
      '  return (',
      '    <ul className="team">',
      '      {team.map(u => (',
      '        <li key={u.id}>',
      '          <img',
      '            src={`' + API + '/avatar/${encodeURIComponent(u.id)}?size=48`}',
      '            alt={u.name}',
      '          />',
      '        </li>',
      '      ))}',
      '    </ul>',
      '  );',
      '}',
    ),
    next: join(
      "import Image from 'next/image';",
      '',
      'const team = [',
      "  { id: '__SEED__', name: 'Alice' },",
      "  { id: 'bob',     name: 'Bob' },",
      "  { id: 'carol',   name: 'Carol' },",
      '];',
      '',
      'export function Team() {',
      '  return (',
      '    <ul className="team">',
      '      {team.map(u => (',
      '        <li key={u.id}>',
      '          <Image',
      '            src={`' + API + '/avatar/${encodeURIComponent(u.id)}?size=48`}',
      '            alt={u.name}',
      '            width={48}',
      '            height={48}',
      '            unoptimized',
      '          />',
      '        </li>',
      '      ))}',
      '    </ul>',
      '  );',
      '}',
    ),
    vue: join(
      '<script setup>',
      'const team = [',
      "  { id: '__SEED__', name: 'Alice' },",
      "  { id: 'bob',     name: 'Bob' },",
      "  { id: 'carol',   name: 'Carol' },",
      '];',
      '</script>',
      '',
      '<template>',
      '  <ul class="team">',
      '    <li v-for="u in team" :key="u.id">',
      '      <img',
      '        :src="`' + API + '/avatar/${encodeURIComponent(u.id)}?size=48`"',
      '        :alt="u.name"',
      '      />',
      '    </li>',
      '  </ul>',
      '</template>',
    ),
    svelte: join(
      '<script>',
      '  const team = [',
      "    { id: '__SEED__', name: 'Alice' },",
      "    { id: 'bob',     name: 'Bob' },",
      "    { id: 'carol',   name: 'Carol' },",
      '  ];',
      '</script>',
      '',
      '<ul class="team">',
      '  {#each team as u (u.id)}',
      '    <li>',
      '      <img',
      '        src={`' + API + '/avatar/${encodeURIComponent(u.id)}?size=48`}',
      '        alt={u.name}',
      '      />',
      '    </li>',
      '  {/each}',
      '</ul>',
    ),
    curl: join(
      '# fetch each teammate in parallel',
      "for id in '__SEED__' bob carol dave; do",
      '  curl -s -o "avatars/$id.svg" \\',
      '    "' + API + '/avatar/$id?size=48"',
      'done',
    ),
    fetch: join(
      "const team = ['__SEED__', 'bob', 'carol', 'dave'];",
      'const svgs = await Promise.all(team.map(id =>',
      '  fetch(`' + API + '/avatar/${encodeURIComponent(id)}?size=48`).then(r => r.text())',
      '));',
    ),
    url: 'GET ' + API + '/avatar/__SEED__?size=48',
  },

  // ── Comment row ────────────────────────────────────────────────────────
  comment: {
    html: join(
      '<article class="comment">',
      '  <img src="' + API + '/avatar/__SEED__?size=40" alt="__SEED__" width="40" height="40" />',
      '  <div>',
      '    <strong>__SEED__</strong>',
      '    <p>Anyone seen the v0.7 deploy?</p>',
      '  </div>',
      '</article>',
    ),
    react: join(
      'export function Comment({ author, body }) {',
      '  return (',
      '    <article className="comment">',
      '      <img',
      '        src={`' + API + '/avatar/${encodeURIComponent(author.id)}?size=40`}',
      '        alt={author.name}',
      '        width={40}',
      '        height={40}',
      '      />',
      '      <div>',
      '        <strong>{author.name}</strong>',
      '        <p>{body}</p>',
      '      </div>',
      '    </article>',
      '  );',
      '}',
    ),
    next: join(
      "import Image from 'next/image';",
      '',
      'export function Comment({ author, body }) {',
      '  return (',
      '    <article className="comment">',
      '      <Image',
      '        src={`' + API + '/avatar/${encodeURIComponent(author.id)}?size=40`}',
      '        alt={author.name}',
      '        width={40}',
      '        height={40}',
      '        unoptimized',
      '      />',
      '      <div>',
      '        <strong>{author.name}</strong>',
      '        <p>{body}</p>',
      '      </div>',
      '    </article>',
      '  );',
      '}',
    ),
    vue: join(
      '<template>',
      '  <article class="comment">',
      '    <img :src="`' + API + '/avatar/${encodeURIComponent(author.id)}?size=40`" :alt="author.name" />',
      '    <div>',
      '      <strong>{{ author.name }}</strong>',
      '      <p>{{ body }}</p>',
      '    </div>',
      '  </article>',
      '</template>',
    ),
    svelte: join(
      '<script>export let author, body;</script>',
      '',
      '<article class="comment">',
      '  <img',
      '    src={`' + API + '/avatar/${encodeURIComponent(author.id)}?size=40`}',
      '    alt={author.name}',
      '  />',
      '  <strong>{author.name}</strong>',
      '  <p>{body}</p>',
      '</article>',
    ),
    curl: "curl -o avatar.svg '" + API + "/avatar/__SEED__?size=40'",
    fetch: "const svg = await fetch('" + API + "/avatar/__SEED__?size=40').then(r => r.text());",
    url: 'GET ' + API + '/avatar/__SEED__?size=40',
  },

  // ── Photo fallback ─────────────────────────────────────────────────────
  fallback: {
    html: join(
      '<!-- Use Navii when the user has no photo -->',
      '<img',
      '  src="https://your-cdn/__SEED__.jpg"',
      '  onerror="this.src=\'' + API + '/avatar/__SEED__?size=64&tileBg=auto\'"',
      '  alt="__SEED__"',
      '  width="64"',
      '  height="64"',
      '/>',
    ),
    react: join(
      'export function Avatar({ user }) {',
      '  const navii = `' + API + '/avatar/${encodeURIComponent(user.id)}?size=64&tileBg=auto`;',
      '  return (',
      '    <img',
      '      src={user.photoUrl ?? navii}',
      '      alt={user.name}',
      '      width={64}',
      '      height={64}',
      '    />',
      '  );',
      '}',
    ),
    next: join(
      "import Image from 'next/image';",
      '',
      'export function Avatar({ user }) {',
      '  const navii = `' + API + '/avatar/${encodeURIComponent(user.id)}?size=64&tileBg=auto`;',
      '  return (',
      '    <Image',
      '      src={user.photoUrl ?? navii}',
      '      alt={user.name}',
      '      width={64}',
      '      height={64}',
      '      unoptimized',
      '    />',
      '  );',
      '}',
    ),
    vue: join(
      '<template>',
      '  <img',
      '    :src="user.photoUrl || `' + API + '/avatar/${encodeURIComponent(user.id)}?size=64&tileBg=auto`"',
      '    :alt="user.name"',
      '    width="64"',
      '    height="64"',
      '  />',
      '</template>',
    ),
    svelte: join(
      '<script>',
      '  export let user;',
      '  $: navii = `' + API + '/avatar/${encodeURIComponent(user.id)}?size=64&tileBg=auto`;',
      '</script>',
      '',
      '<img src={user.photoUrl || navii} alt={user.name} width="64" height="64" />',
    ),
    curl: "curl -fsS -o avatar.svg '" + API + "/avatar/__SEED__?size=64&tileBg=auto' || echo 'using local fallback'",
    fetch: join(
      'const url = user.photoUrl ?? `' + API + '/avatar/${encodeURIComponent(user.id)}?size=64&tileBg=auto`;',
      'const res = await fetch(url);',
    ),
    url: 'GET ' + API + '/avatar/__SEED__?size=64&tileBg=auto',
  },

  // ── Group stack ────────────────────────────────────────────────────────
  group: {
    html: '<img src="' + API + '/group?seeds=__SEED__,bob,carol,dave,eve&size=64&overlap=0.32" alt="team" />',
    react: join(
      'function TeamStack({ members }) {',
      '  const ids = members.map(m => m.id).join(",");',
      '  const url = `' + API + '/group?seeds=${ids}&size=64&overlap=0.32`;',
      '  return <img src={url} alt={`${members.length} members`} />;',
      '}',
    ),
    next: join(
      "import Image from 'next/image';",
      '',
      'export function TeamStack({ members }) {',
      '  const ids = members.map(m => m.id).join(",");',
      '  const url = `' + API + '/group?seeds=${ids}&size=64&overlap=0.32`;',
      '  return <Image src={url} alt="team" width={300} height={64} unoptimized />;',
      '}',
    ),
    vue: join(
      '<script setup>',
      'const props = defineProps([\'members\']);',
      '</script>',
      '',
      '<template>',
      '  <img :src="`' + API + '/group?seeds=${members.map(m => m.id).join(\',\')}&size=64&overlap=0.32`" alt="team" />',
      '</template>',
    ),
    svelte: join(
      '<script>export let members;</script>',
      '',
      '<img',
      '  src={`' + API + '/group?seeds=${members.map(m => m.id).join(",")}&size=64&overlap=0.32`}',
      '  alt="team"',
      '/>',
    ),
    curl: "curl -o team.svg '" + API + "/group?seeds=__SEED__,bob,carol,dave,eve&size=64&overlap=0.32'",
    fetch: join(
      'const ids = members.map(m => m.id).join(",");',
      'const svg = await fetch(`' + API + '/group?seeds=${ids}&size=64&overlap=0.32`).then(r => r.text());',
    ),
    url: 'GET ' + API + '/group?seeds=__SEED__,bob,carol,dave,eve&size=64&overlap=0.32',
  },

  // ── Just the URL (raw) ─────────────────────────────────────────────────
  url: {
    curl: "curl '" + API + "/avatar/__SEED__?size=320&animated=1'",
    fetch: "await fetch('" + API + "/avatar/__SEED__?size=320&animated=1');",
    url: 'GET ' + API + '/avatar/__SEED__?size=320&animated=1',
    html: 'GET ' + API + '/avatar/__SEED__?size=320&animated=1',
    react: 'GET ' + API + '/avatar/__SEED__?size=320&animated=1',
    next: 'GET ' + API + '/avatar/__SEED__?size=320&animated=1',
    vue: 'GET ' + API + '/avatar/__SEED__?size=320&animated=1',
    svelte: 'GET ' + API + '/avatar/__SEED__?size=320&animated=1',
  },
};

// Escape `<` to its unicode form so substrings like "</script>" inside the
// serialized JSON do not prematurely terminate the host <script> block when
// this constant is inlined into landing.html. JSON.parse on the browser side
// (or JS evaluation as an object literal) restores the original characters.
export const TEMPLATES_JSON = JSON.stringify(TEMPLATES).replace(/</g, '\\u003c');
